package color

var colorList map[string]string

func init() {
	colorList = make(map[string]string, 0)
	colorList["black"] = "#000000"
	colorList["silver"] = "#c0c0c0"
	colorList["gray"] = "#808080"
	colorList["white"] = "#ffffff"
	colorList["maroon"] = "#800000"
	colorList["red"] = "#ff0000"
	colorList["purple"] = "#800080"
	colorList["fuchsia"] = "#ff00ff"
	colorList["green"] = "#008000"
	colorList["lime"] = "#00ff00"
	colorList["olive"] = "#808000"
	colorList["yellow"] = "#ffff00"
	colorList["navy"] = "#000080"
	colorList["blue"] = "#0000ff"
	colorList["teal"] = "#008080"
	colorList["aqua"] = "#00ffff"
	colorList["antiquewhite"] = "#faebd7"
	colorList["aquamarine"] = "#7fffd4"
	colorList["azure"] = "#f0ffff"
	colorList["beige"] = "#f5f5dc"
	colorList["bisque"] = "#ffe4c4"
	colorList["blanchedalmond"] = "#ffebcd"
	colorList["blueviolet"] = "#8a2be2"
	colorList["brown"] = "#a52a2a"
	colorList["burlywood"] = "#deb887"
	colorList["cadetblue"] = "#5f9ea0"
	colorList["chartreuse"] = "#7fff00"
	colorList["chocolate"] = "#d2691e"
	colorList["coral"] = "#ff7f50"
	colorList["cornflowerblue"] = "#6495ed"
	colorList["cornsilk"] = "#fff8dc"
	colorList["crimson"] = "#dc143c"
	colorList["cyan"] = "#00ffff"
	colorList["darkblue"] = "#00008b"
	colorList["darkcyan"] = "#008b8b"
	colorList["darkgoldenrod"] = "#b8860b"
	colorList["darkgray"] = "#a9a9a9"
	colorList["darkgreen"] = "#006400"
	colorList["darkgrey"] = "#a9a9a9"
	colorList["darkkhaki"] = "#bdb76b"
	colorList["darkmagenta"] = "#8b008b"
	colorList["darkolivegreen"] = "#556b2f"
	colorList["darkorange"] = "#ff8c00"
	colorList["darkorchid"] = "#9932cc"
	colorList["darkred"] = "#8b0000"
	colorList["darksalmon"] = "#e9967a"
	colorList["darkseagreen"] = "#8fbc8f"
	colorList["darkslateblue"] = "#483d8b"
	colorList["darkslategray"] = "#2f4f4f"
	colorList["darkslategrey"] = "#2f4f4f"
	colorList["darkturquoise"] = "#00ced1"
	colorList["darkviolet"] = "#9400d3"
	colorList["deeppink"] = "#ff1493"
	colorList["deepskyblue"] = "#00bfff"
	colorList["dimgray"] = "#696969"
	colorList["dimgrey"] = "#696969"
	colorList["dodgerblue"] = "#1e90ff"
	colorList["firebrick"] = "#b22222"
	colorList["floralwhite"] = "#fffaf0"
	colorList["forestgreen"] = "#228b22"
	colorList["gainsboro"] = "#dcdcdc"
	colorList["ghostwhite"] = "#f8f8ff"
	colorList["gold"] = "#ffd700"
	colorList["goldenrod"] = "#daa520"
	colorList["greenyellow"] = "#adff2f"
	colorList["grey"] = "#808080"
	colorList["honeydew"] = "#f0fff0"
	colorList["hotpink"] = "#ff69b4"
	colorList["indianred"] = "#cd5c5c"
	colorList["indigo"] = "#4b0082"
	colorList["ivory"] = "#fffff0"
	colorList["khaki"] = "#f0e68c"
	colorList["lavender"] = "#e6e6fa"
	colorList["lavenderblush"] = "#fff0f5"
	colorList["lawngreen"] = "#7cfc00"
	colorList["lemonchiffon"] = "#fffacd"
	colorList["lightblue"] = "#add8e6"
	colorList["lightcoral"] = "#f08080"
	colorList["lightcyan"] = "#e0ffff"
	colorList["lightgoldenrodyellow"] = "#fafad2"
	colorList["lightgray"] = "#d3d3d3"
	colorList["lightgreen"] = "#90ee90"
	colorList["lightgrey"] = "#d3d3d3"
	colorList["lightpink"] = "#ffb6c1"
	colorList["lightsalmon"] = "#ffa07a"
	colorList["lightseagreen"] = "#20b2aa"
	colorList["lightskyblue"] = "#87cefa"
	colorList["lightslategray"] = "#778899"
	colorList["lightslategrey"] = "#778899"
	colorList["lightsteelblue"] = "#b0c4de"
	colorList["lightyellow"] = "#ffffe0"
	colorList["limegreen"] = "#32cd32"
	colorList["linen"] = "#faf0e6"
	colorList["magenta"] = "#ff00ff"
	colorList["mediumaquamarine"] = "#66cdaa"
	colorList["mediumblue"] = "#0000cd"
	colorList["mediumorchid"] = "#ba55d3"
	colorList["mediumpurple"] = "#9370db"
	colorList["mediumseagreen"] = "#3cb371"
	colorList["mediumslateblue"] = "#7b68ee"
	colorList["mediumspringgreen"] = "#00fa9a"
	colorList["mediumturquoise"] = "#48d1cc"
	colorList["mediumvioletred"] = "#c71585"
	colorList["midnightblue"] = "#191970"
	colorList["mintcream"] = "#f5fffa"
	colorList["mistyrose"] = "#ffe4e1"
	colorList["moccasin"] = "#ffe4b5"
	colorList["navajowhite"] = "#ffdead"
	colorList["oldlace"] = "#fdf5e6"
	colorList["olivedrab"] = "#6b8e23"
	colorList["orangered"] = "#ff4500"
	colorList["orchid"] = "#da70d6"
	colorList["palegoldenrod"] = "#eee8aa"
	colorList["palegreen"] = "#98fb98"
	colorList["paleturquoise"] = "#afeeee"
	colorList["palevioletred"] = "#db7093"
	colorList["papayawhip"] = "#ffefd5"
	colorList["peachpuff"] = "#ffdab9"
	colorList["peru"] = "#cd853f"
	colorList["pink"] = "#ffc0cb"
	colorList["plum"] = "#dda0dd"
	colorList["powderblue"] = "#b0e0e6"
	colorList["rosybrown"] = "#bc8f8f"
	colorList["royalblue"] = "#4169e1"
	colorList["saddlebrown"] = "#8b4513"
	colorList["salmon"] = "#fa8072"
	colorList["sandybrown"] = "#f4a460"
	colorList["seagreen"] = "#2e8b57"
	colorList["seashell"] = "#fff5ee"
	colorList["sienna"] = "#a0522d"
	colorList["skyblue"] = "#87ceeb"
	colorList["slateblue"] = "#6a5acd"
	colorList["slategray"] = "#708090"
	colorList["slategrey"] = "#708090"
	colorList["snow"] = "#fffafa"
	colorList["springgreen"] = "#00ff7f"
	colorList["steelblue"] = "4682b4"
	colorList["tan"] = "#d2b48c"
	colorList["thistle"] = "#d8bfd8"
	colorList["tomato"] = "#ff6347"
	colorList["turquoise"] = "#40e0d0"
	colorList["violet"] = "#ee82ee"
	colorList["wheat"] = "#f5deb3"
	colorList["whitesmoke"] = "#f5f5f5"
	colorList["yellowgreen"] = "#9acd32"
}

//ToHexa takes a liteal color such as 'orange' in parameter and returns the hex code
//corresponding to the color, if the color is not found '#ffffff' is returned by default
func ToHexa(literal string) string {
	hex, ok := colorList[literal]
	if ok {
		return hex
	}
	return colorList["black"]
}

//ToLiteral takes a hex value such as '#ffffff' in parameter and returns the literal
//color corresponding to the value, if no value is found 'black' is returned by default
func ToLiteral(hex string) string {
	for literal, hexa := range colorList {
		if hexa == hex {
			return literal
		}
	}
	return "black"
}
